### ISSUE TITLE
autocomplete_generator ends in `KeyError: 'selector'`

### ISSUE THREAD

**Issue by ALERTua** [dmamelin/pyscript_autocomplete#1]
Going through the installation process. Got an exception while running autocomplete_generator:
```
2023-12-11 10:21:21.937 ERROR (MainThread) [custom_components.pyscript.apps.pyscript_autocomplete.autocomplete_generator] Exception in <apps.pyscript_autocomplete.autocomplete_generator> line 65:
                    for selector_id, selector in field["selector"].items():
                                                       ^
KeyError: 'selector'
```
After adding a debug print for field names and fields I came out with a defective one:
`device_id: {'description': 'Device ID of device to change datapoint value for', 'example': '11100118278aab4de001'}`

After adding the field existence check, the script ran ok:
```
if 'selector' not in field.keys():
    continue
```

**Comment by dmamelin** [comment]
fixed in 180fe7c092131260da7d2dc74421a46cca98fb2d
