### ISSUE TITLE
pyscript_autocomplete usage inside pyscript/modules and pyscript/apps

### ISSUE THREAD

**Issue by ALERTua** [dmamelin/pyscript_autocomplete#12]
I struggle enabling syntax highlighting inside `pyscript/modules` and `pyscript/apps`.
I managed to succeed only by copying `pyscript/pyscript_mock` to `pyscript/modules/pyscript_mock`, emptying `pyscript/modules/pyscript_mock/__init__.py`, and using it as a module by importing:
```
from pyscript_mock.pyscript_builtins import *
from pyscript_mock.pyscript_generated import *
```
![image](https://github.com/dmamelin/pyscript_autocomplete/assets/8375129/faab8de4-e03b-45c3-b18e-99bdc2e99bbd)
but this solution has to be a part of the generation service to be viable. and the copying does not look pretty.

Any ideas?

**Comment by dmamelin** [comment]
For `apps` no need to copy anything
Mark `pyscript/pyscript_mock` as source root
But for `modules` I don't have solutions right now. I think i need to make a single loader that will detect the environment. I did experiments, but I didn’t get stable work in pycharm, vscode and pyscript

**Comment by ALERTua** [comment]
Alas, marking `pyscript/pyscript_mock` as source root, and importing `from pyscript_mock import *` doesn't work for `apps` for me in PyCharm.

**Comment by dmamelin** [comment]
That's strange, it works for me in PyCharm 2024.1 EAP.
But that's not important anymore, I've reworked the loader and will commit soon.

**Comment by dmamelin** [comment]
@ALERTua check last commit :) tested in PyCharm and VSCode

**Comment by ALERTua** [comment]
Thank you, it works perfectly!
