### ISSUE TITLE
ModuleNotFoundError: No module named 'pyscript_mock'

### ISSUE THREAD

**Issue by Hugo-Persson** [dmamelin/pyscript_autocomplete#15]
I get the following error:
```
homeassistant-1  | 2024-05-02 22:36:21.652 ERROR (MainThread) [custom_components.pyscript.apps.pyscript_autocomplete] Exception in </config/pyscript/apps/pyscript_autocomplete/__init__.py> line 14:
homeassistant-1  |     from pyscript_mock import *
homeassistant-1  |     ^
homeassistant-1  | ModuleNotFoundError: No module named 'pyscript_mock'
```

Does anyone know why?

**Comment by contagon** [comment]
I was also getting the same error. Probably not the official solution, but I commented out that line, then called the `pyscript.autocomplete_generator` service, then re-commented it in, and things seemed to work after that.

**Comment by ALERTua** [comment]
@dmamelin I guess pyscript_mock shouldn't be imported before it is generated?

**Comment by Hugo-Persson** [comment]
@contagon suggestion worked for me
